import { readdir, readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.resolve(root, '../디자인에셋');
const out = path.resolve(root, '../프론트/public/assets');
const rpg = 'Pixel Art (6364)/RPG (1437)';
const parts = `${rpg}/Characters (1094)/Make-Your-Own Pieces (587)`;
await mkdir(out, { recursive: true });
const manifest = [];
async function walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) { await walk(file); continue; }
    const data = await readFile(file);
    manifest.push({ source: path.relative(source, file).replaceAll('\\', '/'), bytes: data.length, sha256: createHash('sha256').update(data).digest('hex'), extension: path.extname(file).slice(1), ...(data.subarray(1, 4).toString() === 'PNG' ? { width: data.readUInt32BE(16), height: data.readUInt32BE(20) } : {}), provenance: 'user-provided', distributionRights: 'unverified', runtime: false });
  }
}
await walk(source);
const selected = {};
async function select(src, name) {
  await copyFile(path.join(source, src), path.join(out, name));
  const record = manifest.find(a => a.source === src);
  if (!record) throw Error(`Missing source ${src}`);
  record.runtime = true;
  selected[name] = { url: `/assets/${name}`, width: record.width, height: record.height, sha256: record.sha256 };
}
await select('GDG 에셋/GDG Assets/gdgoc-horizontal.svg', 'gdg-horizontal.svg');
await select('GDG 에셋/GDG Assets/gdglogo.svg', 'gdg-mark.svg');
await select('GDG 에셋/Illustration/2026/illust_globalcampus_withgrass.png', 'campus.png');
const avatars = [];
const bodyShapes = ['average', 'dainty', 'heavy'];
for (const [i, body] of bodyShapes.entries()) {
  const hairDir = `${parts}/Hair/${body}_body`;
  const hairs = (await readdir(path.join(source, hairDir))).sort();
  const hair = hairs.find(x => x.includes('short') && x.includes('black')) ?? hairs.find(x => x.includes('brown'));
  const layers = [`${parts}/Bodies/chara_body_${body}_light.png`, `${parts}/Clothing/${body}_body/${body}_casual_${['white', 'pink', 'green'][i]}.png`, `${hairDir}/${hair}`];
  for (const [layer, src] of layers.entries()) await select(src, `avatar-${i}-${layer}.png`);
  avatars.push({ id: i, body, layers: layers.map((_, n) => `/assets/avatar-${i}-${n}.png`), frameWidth: 16, frameHeight: 16, columns: 3, rows: { down: 0, left: 1, right: 2, up: 3 }, idleColumn: 1, anchor: [0.5, 1] });
}
const skinTones = (await readdir(path.join(source, `${parts}/Bodies`)))
  .filter(file => file.startsWith('chara_body_average_') && file.endsWith('.png'))
  .map(file => file.slice('chara_body_average_'.length, -'.png'.length)).sort();
async function commonPartOptions(folder, stripPrefix) {
  const folders = await Promise.all(bodyShapes.map(async body => {
    const files = await readdir(path.join(source, `${parts}/${folder}/${body}_body`));
    return new Set(files.filter(file => file.endsWith('.png')).map(file => file.slice(stripPrefix(body).length, -'.png'.length)));
  }));
  return [...folders[0]].filter(id => folders.every(items => items.has(id))).sort();
}
const clothing = await commonPartOptions('Clothing', body => `${body}_`);
const hair = await commonPartOptions('Hair', body => `${body}_`);
const avatarOptions = { bodyShapes, skinTones, clothing, hair, defaults: { skin: 'light', clothing: ['casual_white', 'casual_pink', 'casual_green'], hair: 'hair_short_black' } };
const avatarPartsDir = path.join(out, 'avatar-parts');
await mkdir(avatarPartsDir, { recursive: true });
async function selectAvatarPart(src, key) {
  await copyFile(path.join(source, src), path.join(avatarPartsDir, `${key}.png`));
  const record = manifest.find(asset => asset.source === src);
  if (!record) throw Error(`Missing source ${src}`);
  record.runtime = true;
}
for (const body of bodyShapes) {
  for (const skin of skinTones)
    await selectAvatarPart(`${parts}/Bodies/chara_body_${body}_${skin}.png`, `body-${body}-${skin}`);
  for (const item of clothing)
    await selectAvatarPart(`${parts}/Clothing/${body}_body/${body}_${item}.png`, `clothing-${body}-${item}`);
  for (const item of hair)
    await selectAvatarPart(`${parts}/Hair/${body}_body/${body}_${item}.png`, `hair-${body}-${item}`);
}
await writeFile(path.join(out, 'avatar-options.json'), JSON.stringify(avatarOptions, null, 2) + '\n');
const javaSet = values => `Set.of(${values.map(value => JSON.stringify(value)).join(', ')})`;
await writeFile(path.join(root, 'modules/auth/src/main/java/town/hufs/auth/AvatarCatalog.java'), `// Generated by scripts/prepare-assets.mjs. Do not edit.\npackage town.hufs.auth;\nimport java.util.Set;\npublic final class AvatarCatalog {\n    public static final Set<String> BODIES = ${javaSet(bodyShapes)};\n    public static final Set<String> SKIN_TONES = ${javaSet(skinTones)};\n    public static final Set<String> CLOTHING = ${javaSet(clothing)};\n    public static final Set<String> HAIR = ${javaSet(hair)};\n    private AvatarCatalog() {}\n    public static String defaultClothing(int avatar) { return switch (avatar) { case 1 -> "casual_pink"; case 2 -> "casual_green"; default -> "casual_white"; }; }\n}\n`);
await writeFile(path.join(root, '../프론트/src/generated/avatarCatalog.ts'), `// Generated by ../백엔드/scripts/prepare-assets.mjs. Do not edit.\nexport const AVATAR_CATALOG = ${JSON.stringify(avatarOptions, null, 2)} as const;\nexport type AvatarCatalog = typeof AVATAR_CATALOG;\n`);
for (const name of ['tree_deciduous_huge_1', 'tree_deciduous_1', 'tree_deciduous_small_1', 'bush_1', 'bush_berries_1', 'house_woodland_1', 'house_woodland_big', 'sign_1', 'tree_stump', 'tree_potted_1', 'campfire_stones', 'crate_1']) {
  await select(`${rpg}/Scenery (343)/Sprites (330)/${name}.png`, `${name}.png`);
}
await select(`${rpg}/Scenery (343)/Tile Sets (5)/rpg_tileset_woodland_town.png`, 'woodland.png');
const avatarSheets = avatars.flatMap(avatar => avatar.layers.map((url, layer) => ({ id: `avatar-${avatar.id}-${layer}`, url, frameWidth: avatar.frameWidth, frameHeight: avatar.frameHeight })));
const assetGroups = {
  brand: { mark: selected['gdg-mark.svg'].url, horizontal: selected['gdg-horizontal.svg'].url, campusIllustration: selected['campus.png'].url },
  avatarSheets,
  campusSquare: ['campus-tree-large','campus-tree','campus-tree-small','campus-bush','campus-berries','campus-house','campus-house-large','campus-sign','gdg-sign'],
  woodlandAtlas: { url: selected['woodland.png'].url, frameWidth: 16, frameHeight: 16 },
};
await writeFile(path.join(root, '../프론트/src/generated/assetGroups.ts'), `// Generated by ../백엔드/scripts/prepare-assets.mjs. Do not edit.\nexport const ASSET_GROUPS = ${JSON.stringify(assetGroups, null, 2)} as const;\n`);
await mkdir(path.join(root, 'assets'), { recursive: true });
manifest.sort((a, b) => a.source.localeCompare(b.source, 'en'));
await writeFile(path.join(root, 'assets/source-manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
await writeFile(path.join(out, 'catalog.json'), JSON.stringify({ use: 'local-development', selected, avatars, groups: assetGroups }, null, 2) + '\n');
console.log(`${manifest.length} source files catalogued; ${Object.keys(selected).length} assets copied. Distribution rights unverified.`);
await import('./create-office-assets.mjs');
await import('./create-sample-map.mjs');
await import('./create-space-templates.mjs');
